# Dockerfile for Frontend Dev Container
# Use an official Node.js runtime as a parent image
FROM mcr.microsoft.com/devcontainers/typescript-node:18

# Set the working directory in the container
WORKDIR /workspaces/Mr-White-Project

# Optional: Install any needed OS packages
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-packages>
